"""Deterministic policy engine and classifiers for IntentFence."""

from .engine import ALLOW_REASON, evaluate_policy
from .models import EvaluationContext, PolicyInput, PolicyResult, RuleOutcome
from .risk import RiskTier, clamp01, combine_risk, risk_tier, state_risk_component, weighted_risk
from .rules import (
    CONSEQUENTIAL_ACTION_UNAPPROVED_RULE_ID,
    CRITICAL_DATA_TO_UNTRUSTED_DESTINATION_RULE_ID,
    EXTERNAL_AUTHORITY_OVERRIDE_RULE_ID,
    FORBIDDEN_RESOURCE_RULE_ID,
    FORBIDDEN_TOOL_RULE_ID,
    PURPOSE_BOUND_DATA_MISUSE_RULE_ID,
    SECRET_ACCESS_UNRELATED_TO_INTENT_RULE_ID,
    WRITE_OUTSIDE_WORKSPACE_RULE_ID,
    ConsequentialActionApprovalRule,
    CriticalDataDestinationRule,
    ExternalContentAuthorityRule,
    ForbiddenResourceRule,
    ForbiddenToolRule,
    PolicyRule,
    PurposeBoundDataRule,
    SecretAccessUnrelatedToIntentRule,
    WriteOutsideWorkspaceRule,
)

__all__ = [
    "ALLOW_REASON",
    "CONSEQUENTIAL_ACTION_UNAPPROVED_RULE_ID",
    "CRITICAL_DATA_TO_UNTRUSTED_DESTINATION_RULE_ID",
    "EXTERNAL_AUTHORITY_OVERRIDE_RULE_ID",
    "FORBIDDEN_RESOURCE_RULE_ID",
    "FORBIDDEN_TOOL_RULE_ID",
    "PURPOSE_BOUND_DATA_MISUSE_RULE_ID",
    "SECRET_ACCESS_UNRELATED_TO_INTENT_RULE_ID",
    "WRITE_OUTSIDE_WORKSPACE_RULE_ID",
    "ConsequentialActionApprovalRule",
    "CriticalDataDestinationRule",
    "EvaluationContext",
    "ExternalContentAuthorityRule",
    "ForbiddenResourceRule",
    "ForbiddenToolRule",
    "PolicyInput",
    "PolicyResult",
    "PolicyRule",
    "PurposeBoundDataRule",
    "RiskTier",
    "RuleOutcome",
    "SecretAccessUnrelatedToIntentRule",
    "WriteOutsideWorkspaceRule",
    "clamp01",
    "combine_risk",
    "evaluate_policy",
    "risk_tier",
    "state_risk_component",
    "weighted_risk",
]
